/* =====================================================================
   FIFA WORLD CUP 2026 — CORE DATA LAYER  (REAL DATA)
   ---------------------------------------------------------------------
   Source: official Final Draw (Washington D.C., 5 Dec 2025) + the
   confirmed match schedule. All kickoff times stored in UTC and shown
   in the visitor's LOCAL timezone. Scores fill in live via live-data.js.
   ===================================================================== */

/* -----------------------------  HOST CITIES & STADIUMS  ----------------------------- */
const STADIUMS = [
  { id:'azteca',   name:'Estadio Azteca',          city:'Mexico City',     country:'Mexico',  cc:'mx', cap:87523, lat:19.3029,  lng:-99.1505, opened:1966, roof:false, wiki:'Estadio_Azteca',          note:'Opening-match venue • the only stadium to host three World Cups' },
  { id:'akron',    name:'Estadio Akron',           city:'Guadalajara',     country:'Mexico',  cc:'mx', cap:49850, lat:20.6815,  lng:-103.4628,opened:2010, roof:false, wiki:'Estadio_Akron',           note:'Home of Chivas de Guadalajara, in Zapopan' },
  { id:'bbva',     name:'Estadio BBVA',            city:'Monterrey',       country:'Mexico',  cc:'mx', cap:53500, lat:25.6694,  lng:-100.2447,opened:2015, roof:false, wiki:'Estadio_BBVA',            note:'"El Gigante de Acero", framed by Cerro de la Silla' },
  { id:'bmo',      name:'BMO Field',               city:'Toronto',         country:'Canada',  cc:'ca', cap:45500, lat:43.6332,  lng:-79.4185, opened:2007, roof:false, wiki:'BMO_Field',               note:"Canada's east-coast home venue" },
  { id:'bcplace',  name:'BC Place',                city:'Vancouver',       country:'Canada',  cc:'ca', cap:54500, lat:49.2768,  lng:-123.1119,opened:1983, roof:true,  wiki:'BC_Place',                note:'Retractable roof on the Pacific waterfront' },
  { id:'mercedes', name:'Mercedes-Benz Stadium',   city:'Atlanta',         country:'USA',     cc:'us', cap:71000, lat:33.7553,  lng:-84.4006, opened:2017, roof:true,  wiki:'Mercedes-Benz_Stadium',   note:'Iconic pinwheel retractable roof • hosts a semi-final' },
  { id:'gillette', name:'Gillette Stadium',        city:'Boston',          country:'USA',     cc:'us', cap:65878, lat:42.0909,  lng:-71.2643, opened:2002, roof:false, wiki:'Gillette_Stadium',        note:'Foxborough, Massachusetts' },
  { id:'att',      name:'AT&T Stadium',            city:'Dallas',          country:'USA',     cc:'us', cap:80000, lat:32.7473,  lng:-97.0945, opened:2009, roof:true,  wiki:'AT&T_Stadium',            note:'"Jerry World" • hosts a semi-final' },
  { id:'nrg',      name:'NRG Stadium',             city:'Houston',         country:'USA',     cc:'us', cap:72220, lat:29.6847,  lng:-95.4107, opened:2002, roof:true,  wiki:'NRG_Stadium',             note:'Retractable roof, Texas heat tamed' },
  { id:'arrowhead',name:'Arrowhead Stadium',       city:'Kansas City',     country:'USA',     cc:'us', cap:76416, lat:39.0489,  lng:-94.4839, opened:1972, roof:false, wiki:'Arrowhead_Stadium',       note:'One of the loudest stadiums on earth' },
  { id:'sofi',     name:'SoFi Stadium',            city:'Los Angeles',     country:'USA',     cc:'us', cap:70240, lat:33.9535,  lng:-118.3392,opened:2020, roof:true,  wiki:'SoFi_Stadium',            note:'$5bn architectural marvel in Inglewood' },
  { id:'hardrock', name:'Hard Rock Stadium',       city:'Miami',           country:'USA',     cc:'us', cap:65326, lat:25.9580,  lng:-80.2389, opened:1987, roof:false, wiki:'Hard_Rock_Stadium',       note:'Canopy-shaded fortress • hosts the third-place match' },
  { id:'metlife',  name:'MetLife Stadium',         city:'New York / NJ',   country:'USA',     cc:'us', cap:82500, lat:40.8128,  lng:-74.0742, opened:2010, roof:false, wiki:'MetLife_Stadium',         note:'★ FINAL VENUE — July 19, 2026' },
  { id:'lincoln',  name:'Lincoln Financial Field', city:'Philadelphia',    country:'USA',     cc:'us', cap:69596, lat:39.9008,  lng:-75.1675, opened:2003, roof:false, wiki:'Lincoln_Financial_Field', note:'"The Linc" in the heart of the city' },
  { id:'levis',    name:"Levi's Stadium",          city:'San Francisco',   country:'USA',     cc:'us', cap:68500, lat:37.4030,  lng:-121.9700,opened:2014, roof:false, wiki:"Levi's_Stadium",          note:'Santa Clara, Silicon Valley showpiece' },
  { id:'lumen',    name:'Lumen Field',             city:'Seattle',         country:'USA',     cc:'us', cap:68740, lat:47.5952,  lng:-122.3316,opened:2002, roof:false, wiki:'Lumen_Field',             note:'Pacific Northwest cauldron of noise' },
];

/* -----------------------------  48 TEAMS in 12 GROUPS (REAL DRAW)  ----------------------------- */
const TEAMS = [
  // GROUP A
  { code:'MEX', name:'Mexico',            cc:'mx',     group:'A', rank:14, conf:'CONCACAF', c1:'#006847', c2:'#ce1126', host:true },
  { code:'RSA', name:'South Africa',      cc:'za',     group:'A', rank:61, conf:'CAF',      c1:'#007749', c2:'#ffb612' },
  { code:'KOR', name:'South Korea',       cc:'kr',     group:'A', rank:23, conf:'AFC',      c1:'#c60c30', c2:'#003478' },
  { code:'CZE', name:'Czechia',           cc:'cz',     group:'A', rank:36, conf:'UEFA',     c1:'#d7141a', c2:'#11457e' },
  // GROUP B
  { code:'CAN', name:'Canada',            cc:'ca',     group:'B', rank:27, conf:'CONCACAF', c1:'#d52b1e', c2:'#ffffff', host:true },
  { code:'BIH', name:'Bosnia & Herzeg.',  cc:'ba',     group:'B', rank:74, conf:'UEFA',     c1:'#002395', c2:'#fecb00' },
  { code:'QAT', name:'Qatar',             cc:'qa',     group:'B', rank:51, conf:'AFC',      c1:'#8a1538', c2:'#ffffff' },
  { code:'SUI', name:'Switzerland',       cc:'ch',     group:'B', rank:17, conf:'UEFA',     c1:'#d52b1e', c2:'#ffffff' },
  // GROUP C
  { code:'BRA', name:'Brazil',            cc:'br',     group:'C', rank:5,  conf:'CONMEBOL', c1:'#fee000', c2:'#009b3a' },
  { code:'MAR', name:'Morocco',           cc:'ma',     group:'C', rank:11, conf:'CAF',      c1:'#c1272d', c2:'#006233' },
  { code:'HAI', name:'Haiti',             cc:'ht',     group:'C', rank:84, conf:'CONCACAF', c1:'#00209f', c2:'#d21034' },
  { code:'SCO', name:'Scotland',          cc:'gb-sct', group:'C', rank:39, conf:'UEFA',     c1:'#0065bf', c2:'#ffffff' },
  // GROUP D
  { code:'USA', name:'United States',     cc:'us',     group:'D', rank:16, conf:'CONCACAF', c1:'#1c2b56', c2:'#b22234', host:true },
  { code:'PAR', name:'Paraguay',          cc:'py',     group:'D', rank:41, conf:'CONMEBOL', c1:'#d52b1e', c2:'#0038a8' },
  { code:'AUS', name:'Australia',         cc:'au',     group:'D', rank:26, conf:'AFC',      c1:'#00843d', c2:'#ffcd00' },
  { code:'TUR', name:'Türkiye',           cc:'tr',     group:'D', rank:28, conf:'UEFA',     c1:'#e30a17', c2:'#ffffff' },
  // GROUP E
  { code:'GER', name:'Germany',           cc:'de',     group:'E', rank:12, conf:'UEFA',     c1:'#000000', c2:'#dd0000' },
  { code:'CUW', name:'Curaçao',           cc:'cw',     group:'E', rank:82, conf:'CONCACAF', c1:'#002b7f', c2:'#f9d616' },
  { code:'CIV', name:"Côte d'Ivoire",     cc:'ci',     group:'E', rank:42, conf:'CAF',      c1:'#f77f00', c2:'#009e60' },
  { code:'ECU', name:'Ecuador',           cc:'ec',     group:'E', rank:22, conf:'CONMEBOL', c1:'#ffd100', c2:'#0033a0' },
  // GROUP F
  { code:'NED', name:'Netherlands',       cc:'nl',     group:'F', rank:7,  conf:'UEFA',     c1:'#f36c21', c2:'#21468b' },
  { code:'JPN', name:'Japan',             cc:'jp',     group:'F', rank:18, conf:'AFC',      c1:'#0033a0', c2:'#bc002d' },
  { code:'SWE', name:'Sweden',            cc:'se',     group:'F', rank:33, conf:'UEFA',     c1:'#006aa7', c2:'#fecc00' },
  { code:'TUN', name:'Tunisia',           cc:'tn',     group:'F', rank:40, conf:'CAF',      c1:'#e70013', c2:'#ffffff' },
  // GROUP G
  { code:'BEL', name:'Belgium',           cc:'be',     group:'G', rank:8,  conf:'UEFA',     c1:'#e30613', c2:'#fdda24' },
  { code:'EGY', name:'Egypt',             cc:'eg',     group:'G', rank:34, conf:'CAF',      c1:'#c8102e', c2:'#000000' },
  { code:'IRN', name:'Iran',              cc:'ir',     group:'G', rank:20, conf:'AFC',      c1:'#239f40', c2:'#da0000' },
  { code:'NZL', name:'New Zealand',       cc:'nz',     group:'G', rank:86, conf:'OFC',      c1:'#000000', c2:'#ffffff' },
  // GROUP H
  { code:'ESP', name:'Spain',             cc:'es',     group:'H', rank:1,  conf:'UEFA',     c1:'#aa151b', c2:'#f1bf00' },
  { code:'CPV', name:'Cape Verde',        cc:'cv',     group:'H', rank:68, conf:'CAF',      c1:'#003893', c2:'#cf2027' },
  { code:'KSA', name:'Saudi Arabia',      cc:'sa',     group:'H', rank:60, conf:'AFC',      c1:'#006c35', c2:'#ffffff' },
  { code:'URU', name:'Uruguay',           cc:'uy',     group:'H', rank:15, conf:'CONMEBOL', c1:'#5cbfeb', c2:'#001b69' },
  // GROUP I
  { code:'FRA', name:'France',            cc:'fr',     group:'I', rank:3,  conf:'UEFA',     c1:'#002395', c2:'#ed2939' },
  { code:'SEN', name:'Senegal',           cc:'sn',     group:'I', rank:19, conf:'CAF',      c1:'#00853f', c2:'#fdef42' },
  { code:'IRQ', name:'Iraq',              cc:'iq',     group:'I', rank:58, conf:'AFC',      c1:'#007a3d', c2:'#ce1126' },
  { code:'NOR', name:'Norway',            cc:'no',     group:'I', rank:29, conf:'UEFA',     c1:'#ba0c2f', c2:'#00205b' },
  // GROUP J
  { code:'ARG', name:'Argentina',         cc:'ar',     group:'J', rank:2,  conf:'CONMEBOL', c1:'#75aadb', c2:'#ffffff' },
  { code:'ALG', name:'Algeria',           cc:'dz',     group:'J', rank:35, conf:'CAF',      c1:'#006233', c2:'#d21034' },
  { code:'AUT', name:'Austria',           cc:'at',     group:'J', rank:24, conf:'UEFA',     c1:'#ed2939', c2:'#ffffff' },
  { code:'JOR', name:'Jordan',            cc:'jo',     group:'J', rank:66, conf:'AFC',      c1:'#007a3d', c2:'#ce1126' },
  // GROUP K
  { code:'POR', name:'Portugal',          cc:'pt',     group:'K', rank:6,  conf:'UEFA',     c1:'#006600', c2:'#da291c' },
  { code:'COD', name:'DR Congo',          cc:'cd',     group:'K', rank:56, conf:'CAF',      c1:'#007fff', c2:'#f7d618' },
  { code:'UZB', name:'Uzbekistan',        cc:'uz',     group:'K', rank:50, conf:'AFC',      c1:'#1eb53a', c2:'#0099b5' },
  { code:'COL', name:'Colombia',          cc:'co',     group:'K', rank:13, conf:'CONMEBOL', c1:'#fcd116', c2:'#003893' },
  // GROUP L
  { code:'ENG', name:'England',           cc:'gb-eng', group:'L', rank:4,  conf:'UEFA',     c1:'#ffffff', c2:'#ce1124' },
  { code:'CRO', name:'Croatia',           cc:'hr',     group:'L', rank:10, conf:'UEFA',     c1:'#171796', c2:'#ce1126' },
  { code:'GHA', name:'Ghana',             cc:'gh',     group:'L', rank:72, conf:'CAF',      c1:'#006b3f', c2:'#fcd116' },
  { code:'PAN', name:'Panama',            cc:'pa',     group:'L', rank:30, conf:'CONCACAF', c1:'#005293', c2:'#d21034' },
];

const TEAM_BY_CODE = Object.fromEntries(TEAMS.map(t => [t.code, t]));
const GROUPS = [...new Set(TEAMS.map(t => t.group))].sort();

/* ---- richer team facts (titles = World Cups won, best = best finish, nick = nickname) ---- */
const TEAM_EXTRA = {
  MEX:{titles:0,best:'Quarter-finals (1970, 1986)',nick:'El Tri'},
  RSA:{titles:0,best:'Group stage',nick:'Bafana Bafana'},
  KOR:{titles:0,best:'4th place (2002)',nick:'Taegeuk Warriors'},
  CZE:{titles:0,best:'Runners-up (1934, 1962 as TCH)',nick:'Národní tým'},
  CAN:{titles:0,best:'Group stage',nick:'Les Rouges'},
  BIH:{titles:0,best:'Group stage (2014)',nick:'Zmajevi'},
  QAT:{titles:0,best:'Group stage (2022)',nick:'The Maroon'},
  SUI:{titles:0,best:'Quarter-finals (1934, 38, 54)',nick:'Nati'},
  BRA:{titles:5,best:'Champions ×5',nick:'Seleção'},
  MAR:{titles:0,best:'4th place (2022)',nick:'Atlas Lions'},
  HAI:{titles:0,best:'Group stage (1974)',nick:'Les Grenadiers'},
  SCO:{titles:0,best:'Group stage',nick:'Tartan Army'},
  USA:{titles:0,best:'3rd place (1930)',nick:'Stars & Stripes'},
  PAR:{titles:0,best:'Round of 16 (1986, 98, 2010)',nick:'La Albirroja'},
  AUS:{titles:0,best:'Round of 16 (2006, 2022)',nick:'Socceroos'},
  TUR:{titles:0,best:'3rd place (2002)',nick:'Ay-Yıldızlılar'},
  GER:{titles:4,best:'Champions ×4',nick:'Die Mannschaft'},
  CUW:{titles:0,best:'Tournament debut',nick:'Debutants',debut:true},
  CIV:{titles:0,best:'Group stage',nick:'Les Éléphants'},
  ECU:{titles:0,best:'Round of 16 (2006)',nick:'La Tri'},
  NED:{titles:0,best:'Runners-up ×3',nick:'Oranje'},
  JPN:{titles:0,best:'Round of 16 (×4)',nick:'Samurai Blue'},
  SWE:{titles:0,best:'Runners-up (1958)',nick:'Blågult'},
  TUN:{titles:0,best:'Group stage',nick:'Eagles of Carthage'},
  BEL:{titles:0,best:'3rd place (2018)',nick:'Red Devils'},
  EGY:{titles:0,best:'Group stage',nick:'The Pharaohs'},
  IRN:{titles:0,best:'Group stage',nick:'Team Melli'},
  NZL:{titles:0,best:'Group stage (1982, 2010)',nick:'All Whites'},
  ESP:{titles:1,best:'Champions (2010)',nick:'La Roja'},
  CPV:{titles:0,best:'Tournament debut',nick:'Blue Sharks',debut:true},
  KSA:{titles:0,best:'Round of 16 (1994)',nick:'Green Falcons'},
  URU:{titles:2,best:'Champions ×2 (1930, 1950)',nick:'La Celeste'},
  FRA:{titles:2,best:'Champions ×2 (1998, 2018)',nick:'Les Bleus'},
  SEN:{titles:0,best:'Quarter-finals (2002)',nick:'Lions of Teranga'},
  IRQ:{titles:0,best:'Group stage (1986)',nick:'Lions of Mesopotamia'},
  NOR:{titles:0,best:'Round of 16 (1998)',nick:'Vikings'},
  ARG:{titles:3,best:'Champions ×3 (1978, 86, 2022)',nick:'La Albiceleste'},
  ALG:{titles:0,best:'Round of 16 (2014)',nick:'Desert Foxes'},
  AUT:{titles:0,best:'3rd place (1954)',nick:'Das Team'},
  JOR:{titles:0,best:'Tournament debut',nick:'Al-Nashama',debut:true},
  POR:{titles:0,best:'3rd place (1966)',nick:'Seleção das Quinas'},
  COD:{titles:0,best:'Round 2 (1974, as Zaire)',nick:'Leopards'},
  UZB:{titles:0,best:'Tournament debut',nick:'White Wolves',debut:true},
  COL:{titles:0,best:'Quarter-finals (2014)',nick:'Los Cafeteros'},
  ENG:{titles:1,best:'Champions (1966)',nick:'Three Lions'},
  CRO:{titles:0,best:'Runners-up (2018)',nick:'Vatreni'},
  GHA:{titles:0,best:'Quarter-finals (2010)',nick:'Black Stars'},
  PAN:{titles:0,best:'Group stage (2018)',nick:'La Marea Roja'},
};
TEAMS.forEach(t => Object.assign(t, TEAM_EXTRA[t.code]||{}));

/* -----------------------------  STAR PLAYERS (REAL, QUALIFIED TEAMS ONLY)  ----------------------------- */
const PLAYERS = [
  { name:'Lionel Messi',       team:'ARG', pos:'FW', num:10, age:38, club:'Inter Miami',        goals:0, assists:0, rating:9.3, hot:true },
  { name:'Kylian Mbappé',      team:'FRA', pos:'FW', num:10, age:27, club:'Real Madrid',        goals:0, assists:0, rating:9.5, hot:true },
  { name:'Lamine Yamal',       team:'ESP', pos:'FW', num:19, age:18, club:'FC Barcelona',       goals:0, assists:0, rating:9.2, hot:true },
  { name:'Erling Haaland',     team:'NOR', pos:'FW', num:9,  age:25, club:'Manchester City',    goals:0, assists:0, rating:9.2, hot:true },
  { name:'Jude Bellingham',    team:'ENG', pos:'MF', num:10, age:22, club:'Real Madrid',        goals:0, assists:0, rating:9.0, hot:true },
  { name:'Vinícius Júnior',    team:'BRA', pos:'FW', num:7,  age:25, club:'Real Madrid',        goals:0, assists:0, rating:9.0, hot:true },
  { name:'Cristiano Ronaldo',  team:'POR', pos:'FW', num:7,  age:41, club:'Al Nassr',           goals:0, assists:0, rating:8.5, hot:true },
  { name:'Mohamed Salah',      team:'EGY', pos:'FW', num:10, age:33, club:'Liverpool',          goals:0, assists:0, rating:8.7, hot:true },
  { name:'Harry Kane',         team:'ENG', pos:'FW', num:9,  age:32, club:'Bayern Munich',      goals:0, assists:0, rating:8.9 },
  { name:'Kevin De Bruyne',    team:'BEL', pos:'MF', num:7,  age:34, club:'Napoli',             goals:0, assists:0, rating:8.7 },
  { name:'Pedri',              team:'ESP', pos:'MF', num:8,  age:23, club:'FC Barcelona',       goals:0, assists:0, rating:8.9 },
  { name:'Rodri',              team:'ESP', pos:'MF', num:16, age:29, club:'Manchester City',    goals:0, assists:0, rating:8.8 },
  { name:'Nico Williams',      team:'ESP', pos:'FW', num:17, age:23, club:'FC Barcelona',       goals:0, assists:0, rating:8.4 },
  { name:'Achraf Hakimi',      team:'MAR', pos:'DF', num:2,  age:27, club:'Paris Saint-Germain',goals:0, assists:0, rating:8.6, hot:true },
  { name:'Florian Wirtz',      team:'GER', pos:'MF', num:10, age:23, club:'Liverpool',          goals:0, assists:0, rating:8.7 },
  { name:'Jamal Musiala',      team:'GER', pos:'MF', num:14, age:23, club:'Bayern Munich',      goals:0, assists:0, rating:8.7 },
  { name:'Kai Havertz',        team:'GER', pos:'FW', num:7,  age:26, club:'Arsenal',            goals:0, assists:0, rating:8.1 },
  { name:'Ousmane Dembélé',    team:'FRA', pos:'FW', num:11, age:28, club:'Paris Saint-Germain',goals:0, assists:0, rating:8.6, hot:true },
  { name:'Aurélien Tchouaméni',team:'FRA', pos:'MF', num:8,  age:26, club:'Real Madrid',        goals:0, assists:0, rating:8.3 },
  { name:'Bukayo Saka',        team:'ENG', pos:'FW', num:7,  age:24, club:'Arsenal',            goals:0, assists:0, rating:8.5 },
  { name:'Phil Foden',         team:'ENG', pos:'MF', num:11, age:25, club:'Manchester City',    goals:0, assists:0, rating:8.4 },
  { name:'Raphinha',           team:'BRA', pos:'FW', num:11, age:29, club:'FC Barcelona',       goals:0, assists:0, rating:8.6, hot:true },
  { name:'Rodrygo',            team:'BRA', pos:'FW', num:10, age:25, club:'Real Madrid',        goals:0, assists:0, rating:8.4 },
  { name:'Bruno Fernandes',    team:'POR', pos:'MF', num:8,  age:31, club:'Manchester United',  goals:0, assists:0, rating:8.5 },
  { name:'Rafael Leão',        team:'POR', pos:'FW', num:15, age:26, club:'AC Milan',           goals:0, assists:0, rating:8.3 },
  { name:'Virgil van Dijk',    team:'NED', pos:'DF', num:4,  age:34, club:'Liverpool',          goals:0, assists:0, rating:8.5 },
  { name:'Cody Gakpo',         team:'NED', pos:'FW', num:11, age:26, club:'Liverpool',          goals:0, assists:0, rating:8.3 },
  { name:'Frenkie de Jong',    team:'NED', pos:'MF', num:21, age:28, club:'FC Barcelona',       goals:0, assists:0, rating:8.4 },
  { name:'Julián Álvarez',     team:'ARG', pos:'FW', num:9,  age:26, club:'Atlético Madrid',    goals:0, assists:0, rating:8.6 },
  { name:'Lautaro Martínez',   team:'ARG', pos:'FW', num:22, age:28, club:'Inter Milan',        goals:0, assists:0, rating:8.5 },
  { name:'Emiliano Martínez',  team:'ARG', pos:'GK', num:23, age:33, club:'Aston Villa',        goals:0, assists:0, rating:8.5 },
  { name:'Thibaut Courtois',   team:'BEL', pos:'GK', num:1,  age:33, club:'Real Madrid',        goals:0, assists:0, rating:8.5 },
  { name:'Federico Valverde',  team:'URU', pos:'MF', num:15, age:27, club:'Real Madrid',        goals:0, assists:0, rating:8.6 },
  { name:'Darwin Núñez',       team:'URU', pos:'FW', num:19, age:26, club:'Al Hilal',           goals:0, assists:0, rating:8.0 },
  { name:'Son Heung-min',      team:'KOR', pos:'FW', num:7,  age:33, club:'LAFC',               goals:0, assists:0, rating:8.4, hot:true },
  { name:'Kim Min-jae',        team:'KOR', pos:'DF', num:3,  age:29, club:'Bayern Munich',      goals:0, assists:0, rating:8.1 },
  { name:'Takefusa Kubo',      team:'JPN', pos:'FW', num:11, age:24, club:'Real Sociedad',      goals:0, assists:0, rating:8.2 },
  { name:'Kaoru Mitoma',       team:'JPN', pos:'FW', num:10, age:28, club:'Brighton',           goals:0, assists:0, rating:8.2 },
  { name:'Christian Pulisic',  team:'USA', pos:'FW', num:10, age:27, club:'AC Milan',           goals:0, assists:0, rating:8.3, hot:true },
  { name:'Weston McKennie',    team:'USA', pos:'MF', num:8,  age:27, club:'Juventus',           goals:0, assists:0, rating:7.9 },
  { name:'Alphonso Davies',    team:'CAN', pos:'DF', num:19, age:25, club:'Bayern Munich',      goals:0, assists:0, rating:8.4, hot:true },
  { name:'Jonathan David',     team:'CAN', pos:'FW', num:20, age:26, club:'Juventus',           goals:0, assists:0, rating:8.1 },
  { name:'Santiago Giménez',   team:'MEX', pos:'FW', num:9,  age:24, club:'AC Milan',           goals:0, assists:0, rating:8.0, hot:true },
  { name:'Edson Álvarez',      team:'MEX', pos:'MF', num:4,  age:28, club:'Fenerbahçe',         goals:0, assists:0, rating:7.8 },
  { name:'Luka Modrić',        team:'CRO', pos:'MF', num:10, age:40, club:'AC Milan',           goals:0, assists:0, rating:8.2, hot:true },
  { name:'Sadio Mané',         team:'SEN', pos:'FW', num:10, age:34, club:'Al Nassr',           goals:0, assists:0, rating:8.1 },
  { name:'James Rodríguez',    team:'COL', pos:'MF', num:10, age:34, club:'Club León',          goals:0, assists:0, rating:7.9 },
  { name:'Luis Díaz',          team:'COL', pos:'FW', num:7,  age:29, club:'Bayern Munich',      goals:0, assists:0, rating:8.3 },
  { name:'Alexander Isak',     team:'SWE', pos:'FW', num:9,  age:26, club:'Liverpool',          goals:0, assists:0, rating:8.3 },
  { name:'Viktor Gyökeres',    team:'SWE', pos:'FW', num:10, age:27, club:'Arsenal',            goals:0, assists:0, rating:8.2, hot:true },
  { name:'Moisés Caicedo',     team:'ECU', pos:'MF', num:23, age:24, club:'Chelsea',            goals:0, assists:0, rating:8.2 },
  { name:'Arda Güler',         team:'TUR', pos:'MF', num:8,  age:21, club:'Real Madrid',        goals:0, assists:0, rating:8.1, hot:true },
  { name:'Hakan Çalhanoğlu',   team:'TUR', pos:'MF', num:10, age:32, club:'Inter Milan',        goals:0, assists:0, rating:8.0 },
  { name:'Granit Xhaka',       team:'SUI', pos:'MF', num:10, age:33, club:'Sunderland',         goals:0, assists:0, rating:7.9 },
  { name:'David Alaba',        team:'AUT', pos:'DF', num:8,  age:33, club:'Real Madrid',        goals:0, assists:0, rating:7.9 },
  { name:'Scott McTominay',    team:'SCO', pos:'MF', num:4,  age:29, club:'Napoli',             goals:0, assists:0, rating:8.0, hot:true },
  { name:'Mohammed Kudus',     team:'GHA', pos:'FW', num:20, age:25, club:'Tottenham',          goals:0, assists:0, rating:8.0 },
  { name:'Chris Wood',         team:'NZL', pos:'FW', num:9,  age:34, club:'Nottm Forest',       goals:0, assists:0, rating:7.6 },
  // ---- deeper squads / all 48 teams represented ----
  { name:'Rodrigo De Paul',    team:'ARG', pos:'MF', num:7,  age:31, club:'Inter Miami',        goals:0, assists:0, rating:8.1 },
  { name:'Enzo Fernández',     team:'ARG', pos:'MF', num:24, age:25, club:'Chelsea',            goals:0, assists:0, rating:8.3 },
  { name:'Alexis Mac Allister',team:'ARG', pos:'MF', num:20, age:27, club:'Liverpool',          goals:0, assists:0, rating:8.4 },
  { name:'Cristian Romero',    team:'ARG', pos:'DF', num:13, age:27, club:'Tottenham',          goals:0, assists:0, rating:8.2 },
  { name:'William Saliba',     team:'FRA', pos:'DF', num:17, age:25, club:'Arsenal',            goals:0, assists:0, rating:8.3 },
  { name:'Michael Olise',      team:'FRA', pos:'FW', num:7,  age:24, club:'Bayern Munich',      goals:0, assists:0, rating:8.3, hot:true },
  { name:'Eduardo Camavinga',  team:'FRA', pos:'MF', num:6,  age:23, club:'Real Madrid',        goals:0, assists:0, rating:8.2 },
  { name:'Dani Olmo',          team:'ESP', pos:'MF', num:21, age:27, club:'FC Barcelona',       goals:0, assists:0, rating:8.3 },
  { name:'Álvaro Morata',      team:'ESP', pos:'FW', num:7,  age:33, club:'Como',               goals:0, assists:0, rating:7.8 },
  { name:'Unai Simón',         team:'ESP', pos:'GK', num:23, age:28, club:'Athletic Club',      goals:0, assists:0, rating:8.1 },
  { name:'Declan Rice',        team:'ENG', pos:'MF', num:4,  age:27, club:'Arsenal',            goals:0, assists:0, rating:8.5 },
  { name:'Cole Palmer',        team:'ENG', pos:'FW', num:24, age:24, club:'Chelsea',            goals:0, assists:0, rating:8.6, hot:true },
  { name:'Trent Alexander-Arnold',team:'ENG',pos:'DF',num:12,age:27,club:'Real Madrid',         goals:0, assists:0, rating:8.2 },
  { name:'Jordan Pickford',    team:'ENG', pos:'GK', num:1,  age:31, club:'Everton',            goals:0, assists:0, rating:8.0 },
  { name:'Bruno Guimarães',    team:'BRA', pos:'MF', num:5,  age:28, club:'Newcastle',          goals:0, assists:0, rating:8.3 },
  { name:'Marquinhos',         team:'BRA', pos:'DF', num:4,  age:31, club:'Paris Saint-Germain',goals:0, assists:0, rating:8.2 },
  { name:'Alisson',            team:'BRA', pos:'GK', num:1,  age:33, club:'Liverpool',          goals:0, assists:0, rating:8.4 },
  { name:'Estêvão',            team:'BRA', pos:'FW', num:19, age:18, club:'Chelsea',            goals:0, assists:0, rating:8.0, hot:true },
  { name:'Bernardo Silva',     team:'POR', pos:'MF', num:10, age:31, club:'Manchester City',    goals:0, assists:0, rating:8.4 },
  { name:'Vitinha',            team:'POR', pos:'MF', num:16, age:26, club:'Paris Saint-Germain',goals:0, assists:0, rating:8.5, hot:true },
  { name:'Diogo Costa',        team:'POR', pos:'GK', num:22, age:26, club:'FC Porto',           goals:0, assists:0, rating:8.2 },
  { name:'Joshua Kimmich',     team:'GER', pos:'MF', num:6,  age:31, club:'Bayern Munich',      goals:0, assists:0, rating:8.4 },
  { name:'Antonio Rüdiger',    team:'GER', pos:'DF', num:2,  age:33, club:'Real Madrid',        goals:0, assists:0, rating:8.1 },
  { name:'Memphis Depay',      team:'NED', pos:'FW', num:10, age:32, club:'Corinthians',        goals:0, assists:0, rating:8.0 },
  { name:'Denzel Dumfries',    team:'NED', pos:'DF', num:22, age:30, club:'Inter Milan',        goals:0, assists:0, rating:8.0 },
  { name:'Xavi Simons',        team:'NED', pos:'MF', num:7,  age:23, club:'Tottenham',          goals:0, assists:0, rating:8.2 },
  { name:'Romelu Lukaku',      team:'BEL', pos:'FW', num:9,  age:33, club:'Napoli',             goals:0, assists:0, rating:8.0 },
  { name:'Jérémy Doku',        team:'BEL', pos:'FW', num:22, age:24, club:'Manchester City',    goals:0, assists:0, rating:8.2 },
  { name:'Martin Ødegaard',    team:'NOR', pos:'MF', num:20, age:27, club:'Arsenal',            goals:0, assists:0, rating:8.5, hot:true },
  { name:'Brahim Díaz',        team:'MAR', pos:'FW', num:10, age:26, club:'Real Madrid',        goals:0, assists:0, rating:8.1 },
  { name:'Patrik Schick',      team:'CZE', pos:'FW', num:9,  age:30, club:'Bayer Leverkusen',   goals:0, assists:0, rating:8.0 },
  { name:'Tomáš Souček',       team:'CZE', pos:'MF', num:8,  age:31, club:'West Ham',           goals:0, assists:0, rating:7.7 },
  { name:'Lyle Foster',        team:'RSA', pos:'FW', num:9,  age:25, club:'Burnley',            goals:0, assists:0, rating:7.4 },
  { name:'Percy Tau',          team:'RSA', pos:'FW', num:11, age:31, club:'Al Ahly',            goals:0, assists:0, rating:7.3 },
  { name:'Edin Džeko',         team:'BIH', pos:'FW', num:11, age:40, club:'Fiorentina',         goals:0, assists:0, rating:7.6 },
  { name:'Akram Afif',         team:'QAT', pos:'FW', num:11, age:29, club:'Al Sadd',            goals:0, assists:0, rating:7.7 },
  { name:'Almoez Ali',         team:'QAT', pos:'FW', num:19, age:29, club:'Al Rayyan',          goals:0, assists:0, rating:7.4 },
  { name:'Miguel Almirón',     team:'PAR', pos:'MF', num:10, age:32, club:'Atlanta United',     goals:0, assists:0, rating:7.6 },
  { name:'Antonio Sanabria',   team:'PAR', pos:'FW', num:9,  age:30, club:'Cremonese',          goals:0, assists:0, rating:7.4 },
  { name:'Mathew Ryan',        team:'AUS', pos:'GK', num:1,  age:34, club:'Roma',               goals:0, assists:0, rating:7.7 },
  { name:'Jackson Irvine',     team:'AUS', pos:'MF', num:22, age:33, club:'St. Pauli',          goals:0, assists:0, rating:7.4 },
  { name:'Leandro Bacuna',     team:'CUW', pos:'MF', num:8,  age:34, club:'Free agent',         goals:0, assists:0, rating:7.0 },
  { name:'Sébastien Haller',   team:'CIV', pos:'FW', num:9,  age:31, club:'Utrecht',            goals:0, assists:0, rating:7.7 },
  { name:'Simon Adingra',      team:'CIV', pos:'FW', num:11, age:24, club:'Sunderland',         goals:0, assists:0, rating:7.8 },
  { name:'Franck Kessié',      team:'CIV', pos:'MF', num:6,  age:29, club:'Al Ahli',            goals:0, assists:0, rating:7.8 },
  { name:'Hannibal Mejbri',    team:'TUN', pos:'MF', num:14, age:23, club:'Burnley',            goals:0, assists:0, rating:7.4 },
  { name:'Mehdi Taremi',       team:'IRN', pos:'FW', num:9,  age:33, club:'Inter Milan',        goals:0, assists:0, rating:7.8 },
  { name:'Sardar Azmoun',      team:'IRN', pos:'FW', num:20, age:31, club:'Shabab Al Ahli',     goals:0, assists:0, rating:7.5 },
  { name:'Ryan Mendes',        team:'CPV', pos:'FW', num:10, age:35, club:'Cova Piedade',       goals:0, assists:0, rating:7.1 },
  { name:'Salem Al-Dawsari',   team:'KSA', pos:'FW', num:10, age:34, club:'Al Hilal',           goals:0, assists:0, rating:7.6 },
  { name:'Firas Al-Buraikan',  team:'KSA', pos:'FW', num:9,  age:25, club:'Al Ahli',            goals:0, assists:0, rating:7.3 },
  { name:'Aymen Hussein',      team:'IRQ', pos:'FW', num:9,  age:29, club:'Al Qadsiah',         goals:0, assists:0, rating:7.2 },
  { name:'Riyad Mahrez',       team:'ALG', pos:'FW', num:7,  age:35, club:'Al Ahli',            goals:0, assists:0, rating:7.9, hot:true },
  { name:'Ismaël Bennacer',    team:'ALG', pos:'MF', num:4,  age:28, club:'AC Milan',           goals:0, assists:0, rating:7.7 },
  { name:'Mousa Al-Tamari',    team:'JOR', pos:'FW', num:7,  age:28, club:'Montpellier',        goals:0, assists:0, rating:7.5 },
  { name:'Yoane Wissa',        team:'COD', pos:'FW', num:11, age:29, club:'Newcastle',          goals:0, assists:0, rating:7.7 },
  { name:'Chancel Mbemba',     team:'COD', pos:'DF', num:5,  age:31, club:'Lille',              goals:0, assists:0, rating:7.6 },
  { name:'Eldor Shomurodov',   team:'UZB', pos:'FW', num:9,  age:31, club:'Roma',               goals:0, assists:0, rating:7.4 },
  { name:'Abbosbek Fayzullaev',team:'UZB', pos:'MF', num:7,  age:22, club:'CSKA Moscow',        goals:0, assists:0, rating:7.5, hot:true },
  { name:'Adalberto Carrasquilla',team:'PAN',pos:'MF',num:6, age:27, club:'Pumas UNAM',         goals:0, assists:0, rating:7.4 },
  { name:'Andy Robertson',     team:'SCO', pos:'DF', num:3,  age:32, club:'Liverpool',          goals:0, assists:0, rating:8.0 },
  { name:'Frantzdy Pierrot',   team:'HAI', pos:'FW', num:9,  age:30, club:'Gaziantep',          goals:0, assists:0, rating:7.2 },
];

/* -----------------------------  MATCH SCHEDULE (REAL FIXTURES, times in UTC)  -----------------------------
   ET (EDT, UTC-4) kickoffs converted to UTC. hs/as fill in live via live-data.js.
--------------------------------------------------------------------------------------------------------- */
const MATCHES = [
  // Matchday 1
  { id:1,  group:'A', home:'MEX', away:'RSA', kickoff:'2026-06-11T19:00:00Z', stadium:'azteca' },
  { id:2,  group:'A', home:'KOR', away:'CZE', kickoff:'2026-06-12T02:00:00Z', stadium:'akron' },
  { id:3,  group:'B', home:'CAN', away:'BIH', kickoff:'2026-06-12T19:00:00Z', stadium:'bmo' },
  { id:4,  group:'D', home:'USA', away:'PAR', kickoff:'2026-06-13T01:00:00Z', stadium:'sofi' },
  { id:5,  group:'B', home:'QAT', away:'SUI', kickoff:'2026-06-13T19:00:00Z', stadium:'levis' },
  { id:6,  group:'C', home:'BRA', away:'MAR', kickoff:'2026-06-13T22:00:00Z', stadium:'metlife' },
  { id:7,  group:'C', home:'HAI', away:'SCO', kickoff:'2026-06-14T01:00:00Z', stadium:'gillette' },
  { id:8,  group:'D', home:'AUS', away:'TUR', kickoff:'2026-06-14T04:00:00Z', stadium:'bcplace' },
  { id:9,  group:'E', home:'GER', away:'CUW', kickoff:'2026-06-14T17:00:00Z', stadium:'nrg' },
  { id:10, group:'F', home:'NED', away:'JPN', kickoff:'2026-06-14T20:00:00Z', stadium:'att' },
  { id:11, group:'E', home:'CIV', away:'ECU', kickoff:'2026-06-14T23:00:00Z', stadium:'lincoln' },
  { id:12, group:'F', home:'SWE', away:'TUN', kickoff:'2026-06-15T02:00:00Z', stadium:'bbva' },
  { id:13, group:'H', home:'ESP', away:'CPV', kickoff:'2026-06-15T17:00:00Z', stadium:'mercedes' },
  { id:14, group:'G', home:'BEL', away:'EGY', kickoff:'2026-06-15T22:00:00Z', stadium:'lumen' },
  { id:15, group:'H', home:'KSA', away:'URU', kickoff:'2026-06-15T22:00:00Z', stadium:'hardrock' },
  { id:16, group:'G', home:'IRN', away:'NZL', kickoff:'2026-06-16T04:00:00Z', stadium:'sofi' },
  { id:17, group:'I', home:'FRA', away:'SEN', kickoff:'2026-06-16T19:00:00Z', stadium:'metlife' },
  { id:18, group:'I', home:'IRQ', away:'NOR', kickoff:'2026-06-16T22:00:00Z', stadium:'gillette' },
  { id:19, group:'J', home:'ARG', away:'ALG', kickoff:'2026-06-17T01:00:00Z', stadium:'arrowhead' },
  { id:20, group:'J', home:'AUT', away:'JOR', kickoff:'2026-06-17T04:00:00Z', stadium:'levis' },
  { id:21, group:'K', home:'POR', away:'COD', kickoff:'2026-06-17T17:00:00Z', stadium:'nrg' },
  { id:22, group:'L', home:'ENG', away:'CRO', kickoff:'2026-06-17T20:00:00Z', stadium:'att' },
  { id:23, group:'L', home:'GHA', away:'PAN', kickoff:'2026-06-17T23:00:00Z', stadium:'bmo' },
  { id:24, group:'K', home:'UZB', away:'COL', kickoff:'2026-06-18T02:00:00Z', stadium:'azteca' },
  // Matchday 2
  { id:25, group:'A', home:'CZE', away:'RSA', kickoff:'2026-06-18T16:00:00Z', stadium:'mercedes' },
  { id:26, group:'B', home:'SUI', away:'BIH', kickoff:'2026-06-18T19:00:00Z', stadium:'sofi' },
  { id:27, group:'B', home:'CAN', away:'QAT', kickoff:'2026-06-18T22:00:00Z', stadium:'bcplace' },
  { id:28, group:'A', home:'MEX', away:'KOR', kickoff:'2026-06-19T03:00:00Z', stadium:'akron' },
  { id:29, group:'D', home:'USA', away:'AUS', kickoff:'2026-06-19T19:00:00Z', stadium:'lumen' },
  { id:30, group:'C', home:'SCO', away:'MAR', kickoff:'2026-06-19T22:00:00Z', stadium:'gillette' },
  { id:31, group:'C', home:'BRA', away:'HAI', kickoff:'2026-06-20T01:00:00Z', stadium:'lincoln' },
  { id:32, group:'D', home:'TUR', away:'PAR', kickoff:'2026-06-20T04:00:00Z', stadium:'levis' },
  { id:33, group:'F', home:'NED', away:'SWE', kickoff:'2026-06-20T17:00:00Z', stadium:'nrg' },
  { id:34, group:'E', home:'GER', away:'CIV', kickoff:'2026-06-20T20:00:00Z', stadium:'bmo' },
  { id:35, group:'E', home:'ECU', away:'CUW', kickoff:'2026-06-21T00:00:00Z', stadium:'arrowhead' },
  { id:36, group:'F', home:'TUN', away:'JPN', kickoff:'2026-06-21T04:00:00Z', stadium:'bbva' },
  { id:37, group:'H', home:'ESP', away:'KSA', kickoff:'2026-06-21T16:00:00Z', stadium:'mercedes' },
  { id:38, group:'G', home:'BEL', away:'IRN', kickoff:'2026-06-21T19:00:00Z', stadium:'sofi' },
  { id:39, group:'H', home:'URU', away:'CPV', kickoff:'2026-06-21T22:00:00Z', stadium:'hardrock' },
  { id:40, group:'G', home:'NZL', away:'EGY', kickoff:'2026-06-22T01:00:00Z', stadium:'bcplace' },
  { id:41, group:'J', home:'ARG', away:'AUT', kickoff:'2026-06-22T17:00:00Z', stadium:'att' },
  { id:42, group:'I', home:'FRA', away:'IRQ', kickoff:'2026-06-22T21:00:00Z', stadium:'lincoln' },
  { id:43, group:'I', home:'NOR', away:'SEN', kickoff:'2026-06-23T00:00:00Z', stadium:'metlife' },
  { id:44, group:'J', home:'JOR', away:'ALG', kickoff:'2026-06-23T03:00:00Z', stadium:'levis' },
  { id:45, group:'K', home:'POR', away:'UZB', kickoff:'2026-06-23T17:00:00Z', stadium:'nrg' },
  { id:46, group:'L', home:'ENG', away:'GHA', kickoff:'2026-06-23T20:00:00Z', stadium:'gillette' },
  { id:47, group:'L', home:'PAN', away:'CRO', kickoff:'2026-06-23T23:00:00Z', stadium:'bmo' },
  { id:48, group:'K', home:'COL', away:'COD', kickoff:'2026-06-24T02:00:00Z', stadium:'akron' },
  // Matchday 3 (simultaneous kickoffs per group)
  { id:49, group:'B', home:'SUI', away:'CAN', kickoff:'2026-06-24T19:00:00Z', stadium:'bcplace' },
  { id:50, group:'B', home:'BIH', away:'QAT', kickoff:'2026-06-24T19:00:00Z', stadium:'lumen' },
  { id:51, group:'C', home:'SCO', away:'BRA', kickoff:'2026-06-24T22:00:00Z', stadium:'hardrock' },
  { id:52, group:'C', home:'MAR', away:'HAI', kickoff:'2026-06-24T22:00:00Z', stadium:'mercedes' },
  { id:53, group:'A', home:'CZE', away:'MEX', kickoff:'2026-06-25T01:00:00Z', stadium:'azteca' },
  { id:54, group:'A', home:'RSA', away:'KOR', kickoff:'2026-06-25T01:00:00Z', stadium:'bbva' },
  { id:55, group:'E', home:'ECU', away:'GER', kickoff:'2026-06-25T20:00:00Z', stadium:'metlife' },
  { id:56, group:'E', home:'CUW', away:'CIV', kickoff:'2026-06-25T20:00:00Z', stadium:'lincoln' },
  { id:57, group:'F', home:'JPN', away:'SWE', kickoff:'2026-06-25T23:00:00Z', stadium:'att' },
  { id:58, group:'F', home:'TUN', away:'NED', kickoff:'2026-06-25T23:00:00Z', stadium:'arrowhead' },
  { id:59, group:'D', home:'TUR', away:'USA', kickoff:'2026-06-26T02:00:00Z', stadium:'sofi' },
  { id:60, group:'D', home:'PAR', away:'AUS', kickoff:'2026-06-26T02:00:00Z', stadium:'levis' },
  { id:61, group:'I', home:'NOR', away:'FRA', kickoff:'2026-06-26T19:00:00Z', stadium:'gillette' },
  { id:62, group:'I', home:'SEN', away:'IRQ', kickoff:'2026-06-26T19:00:00Z', stadium:'bmo' },
  { id:63, group:'H', home:'CPV', away:'KSA', kickoff:'2026-06-27T00:00:00Z', stadium:'nrg' },
  { id:64, group:'H', home:'URU', away:'ESP', kickoff:'2026-06-27T00:00:00Z', stadium:'akron' },
  { id:65, group:'G', home:'EGY', away:'IRN', kickoff:'2026-06-27T03:00:00Z', stadium:'lumen' },
  { id:66, group:'G', home:'NZL', away:'BEL', kickoff:'2026-06-27T03:00:00Z', stadium:'bcplace' },
  { id:67, group:'L', home:'PAN', away:'ENG', kickoff:'2026-06-27T21:00:00Z', stadium:'metlife' },
  { id:68, group:'L', home:'CRO', away:'GHA', kickoff:'2026-06-27T21:00:00Z', stadium:'lincoln' },
  { id:69, group:'K', home:'COL', away:'POR', kickoff:'2026-06-27T23:30:00Z', stadium:'hardrock' },
  { id:70, group:'K', home:'COD', away:'UZB', kickoff:'2026-06-27T23:30:00Z', stadium:'mercedes' },
  { id:71, group:'J', home:'ALG', away:'AUT', kickoff:'2026-06-28T02:00:00Z', stadium:'arrowhead' },
  { id:72, group:'J', home:'JOR', away:'ARG', kickoff:'2026-06-28T02:00:00Z', stadium:'att' },

  // ---- KNOCKOUT BRACKET (official slot structure + dates; teams resolve from results) ----
  // homeSlot/awaySlot tokens: 1X=group winner, 2X=runner-up, 3XYZ=best third from listed groups, W##/L##=winner/loser of match ##
  { id:73, kickoff:'2026-06-28T20:00:00Z', stadium:'sofi',     stage:'Round of 32', homeSlot:'2A', awaySlot:'2B' },
  { id:74, kickoff:'2026-06-29T16:00:00Z', stadium:'bbva',     stage:'Round of 32', homeSlot:'1E', awaySlot:'3ABCDF' },
  { id:75, kickoff:'2026-06-29T20:00:00Z', stadium:'mercedes', stage:'Round of 32', homeSlot:'1F', awaySlot:'2C' },
  { id:76, kickoff:'2026-06-29T23:00:00Z', stadium:'att',      stage:'Round of 32', homeSlot:'1C', awaySlot:'2F' },
  { id:77, kickoff:'2026-06-30T16:00:00Z', stadium:'akron',    stage:'Round of 32', homeSlot:'1I', awaySlot:'3CDFGH' },
  { id:78, kickoff:'2026-06-30T20:00:00Z', stadium:'metlife',  stage:'Round of 32', homeSlot:'2E', awaySlot:'2I' },
  { id:79, kickoff:'2026-06-30T23:00:00Z', stadium:'azteca',   stage:'Round of 32', homeSlot:'1A', awaySlot:'3CEFHI' },
  { id:80, kickoff:'2026-07-01T16:00:00Z', stadium:'levis',    stage:'Round of 32', homeSlot:'1L', awaySlot:'3EHIJK' },
  { id:81, kickoff:'2026-07-01T20:00:00Z', stadium:'bcplace',  stage:'Round of 32', homeSlot:'1D', awaySlot:'3BEFIJ' },
  { id:82, kickoff:'2026-07-01T23:00:00Z', stadium:'nrg',      stage:'Round of 32', homeSlot:'1G', awaySlot:'3AEHIJ' },
  { id:83, kickoff:'2026-07-02T16:00:00Z', stadium:'bmo',      stage:'Round of 32', homeSlot:'2K', awaySlot:'2L' },
  { id:84, kickoff:'2026-07-02T20:00:00Z', stadium:'arrowhead',stage:'Round of 32', homeSlot:'1H', awaySlot:'2J' },
  { id:85, kickoff:'2026-07-02T23:00:00Z', stadium:'hardrock', stage:'Round of 32', homeSlot:'1B', awaySlot:'3EFGIJ' },
  { id:86, kickoff:'2026-07-03T16:00:00Z', stadium:'lincoln',  stage:'Round of 32', homeSlot:'1J', awaySlot:'2H' },
  { id:87, kickoff:'2026-07-03T20:00:00Z', stadium:'lumen',    stage:'Round of 32', homeSlot:'1K', awaySlot:'3DEIJL' },
  { id:88, kickoff:'2026-07-03T23:30:00Z', stadium:'gillette', stage:'Round of 32', homeSlot:'2D', awaySlot:'2G' },

  { id:89, kickoff:'2026-07-04T20:00:00Z', stadium:'sofi',     stage:'Round of 16', homeSlot:'W74', awaySlot:'W77' },
  { id:90, kickoff:'2026-07-04T23:00:00Z', stadium:'att',      stage:'Round of 16', homeSlot:'W73', awaySlot:'W75' },
  { id:91, kickoff:'2026-07-05T20:00:00Z', stadium:'metlife',  stage:'Round of 16', homeSlot:'W76', awaySlot:'W78' },
  { id:92, kickoff:'2026-07-05T23:00:00Z', stadium:'mercedes', stage:'Round of 16', homeSlot:'W79', awaySlot:'W80' },
  { id:93, kickoff:'2026-07-06T20:00:00Z', stadium:'lincoln',  stage:'Round of 16', homeSlot:'W83', awaySlot:'W84' },
  { id:94, kickoff:'2026-07-06T23:00:00Z', stadium:'bcplace',  stage:'Round of 16', homeSlot:'W81', awaySlot:'W82' },
  { id:95, kickoff:'2026-07-07T20:00:00Z', stadium:'azteca',   stage:'Round of 16', homeSlot:'W86', awaySlot:'W88' },
  { id:96, kickoff:'2026-07-07T23:00:00Z', stadium:'arrowhead',stage:'Round of 16', homeSlot:'W85', awaySlot:'W87' },

  { id:97,  kickoff:'2026-07-09T23:00:00Z', stadium:'mercedes', stage:'Quarter-final', homeSlot:'W89', awaySlot:'W90' },
  { id:98,  kickoff:'2026-07-10T23:00:00Z', stadium:'sofi',     stage:'Quarter-final', homeSlot:'W93', awaySlot:'W94' },
  { id:99,  kickoff:'2026-07-11T19:00:00Z', stadium:'metlife',  stage:'Quarter-final', homeSlot:'W91', awaySlot:'W92' },
  { id:100, kickoff:'2026-07-11T23:00:00Z', stadium:'arrowhead',stage:'Quarter-final', homeSlot:'W95', awaySlot:'W96' },

  { id:101, kickoff:'2026-07-14T23:00:00Z', stadium:'att',      stage:'Semi-final', homeSlot:'W97', awaySlot:'W98' },
  { id:102, kickoff:'2026-07-15T23:00:00Z', stadium:'mercedes', stage:'Semi-final', homeSlot:'W99', awaySlot:'W100' },
  { id:103, kickoff:'2026-07-18T19:00:00Z', stadium:'hardrock', stage:'Third place', homeSlot:'L101', awaySlot:'L102' },
  { id:104, kickoff:'2026-07-19T19:00:00Z', stadium:'metlife',  stage:'FINAL', homeSlot:'W101', awaySlot:'W102' },
];
// stage label for group matches
MATCHES.forEach(m => { if(!m.stage && m.group) m.stage = 'Group '+m.group; if(m.hs===undefined){m.hs=null;m.as=null;} });

/* Key tournament dates */
const TOURNAMENT = {
  name:'FIFA World Cup 2026™',
  hosts:'United States · Canada · Mexico',
  start:'2026-06-11T19:00:00Z',   // Mexico vs South Africa, Estadio Azteca
  final:'2026-07-19T19:00:00Z',
  teams:48, groups:12, matches:104, cities:16,
};

/* -----------------------------  NEWS  ----------------------------- */
const NEWS = [
  { id:1, cat:'Headline', date:'2026-06-11T12:00:00Z', img:'azteca', title:'It begins! Mexico host South Africa to open World Cup 2026 at the Azteca',
    blurb:'The first-ever 48-team World Cup kicks off in Mexico City — a rematch of the 2010 opener, 16 years on, at the only stadium ever to host three World Cups.' },
  { id:2, cat:'Analysis', date:'2026-06-10T15:30:00Z', img:'metlife', title:'Power Rankings: Spain top, with Argentina, France and England chasing',
    blurb:'World No.1 Spain headline a stacked field. Our model weighs form, squad value and draw difficulty to rank all 48 nations before kick-off.' },
  { id:3, cat:'Feature', date:'2026-06-09T09:00:00Z', img:'sofi', title:'Across a continent: 16 stadiums, three nations, four time zones',
    blurb:'From the historic Azteca to SoFi\'s glittering canopy, tour the venues that will stage the biggest World Cup ever — and the final at MetLife.' },
  { id:4, cat:'Stars', date:'2026-06-08T18:45:00Z', img:'hardrock', title:'Messi\'s last dance: Argentina chase back-to-back crowns',
    blurb:'At 38, the captain leads the holders into Group J. Can Lautaro, Julián Álvarez and a new generation defend the title won in 2022?' },
  { id:5, cat:'Wonderkids', date:'2026-06-07T11:20:00Z', img:'att', title:'Yamal, Wirtz, Güler: the teenagers ready to light up 2026',
    blurb:'A golden generation arrives. We profile the under-23 stars — led by Spain\'s Lamine Yamal — who could define the tournament.' },
  { id:6, cat:'Fans', date:'2026-06-06T08:10:00Z', img:'lumen', title:'Follow every kick in your time zone — never miss a goal',
    blurb:'With matches across four U.S./Canada/Mexico time zones, here\'s your guide to local kick-off times and the unmissable group fixtures.' },
  { id:7, cat:'Group A', date:'2026-06-05T16:00:00Z', img:'akron', title:'Hosts Mexico eye fast start against South Africa and Korea',
    blurb:'Drawn with South Africa, South Korea and Czechia, El Tri have a winnable group — but Son Heung-min\'s Korea will fancy their chances.' },
  { id:8, cat:'Records', date:'2026-06-04T13:30:00Z', img:'mercedes', title:'104 matches, 39 days: inside the largest World Cup ever',
    blurb:'A new format means more drama than ever. We break down the expanded schedule, the new Round of 32 and the road to MetLife.' },
];
